export const INITIAL_FORM = Object.freeze({
	dni: "",
	name: "",
	surname: "",
	gender: "",
	birthdate: "",
	email: "",
	phone: "",
	occupation: "",
	originDepartmentId: 0,
	originProvinceId: 0,
	originDistrictId: 0,
	originAddress: "",
	studiesInstitutionType: 0,
	studiesCompleted: true,
	studiesEndYear: "",
	studiesDepartmentId: 0,
	studiesProvinceId: 0,
	studiesDistrictId: 0,
	studiesAddress: "",
	studiesInstitutionName: "",
	representativeFullName: "",
	representativeFamilyRelationshipId: 0,
	representativeEmail: "",
	representativePhone: "",
	representativeOccupation: "",
	majorId: 0,
	facultyId: 0,
	dniFilename: {
		base64: "",
		filename: "",
	},
	studyCertificateFilename: {
		base64: "",
		filename: "",
	},
	compromiseStudyCertificateFilename: {
		base64: "",
		filename: "",
	},
	documentaryProgressFiveYearFilename: {
		base64: "",
		filename: "",
	},
	statementNotCriminalFilename: {
		base64: "",
		filename: "",
	},
});
export const INITIAL_ERRORS = Object.freeze({
	dni: null,
	name: null,
	surname: null,
	gender: null,
	birthdate: null,
	email: null,
	phone: null,
	occupation: null,
	originDepartmentId: null,
	originProvinceId: null,
	originDistrictId: null,
	originAddress: null,
	studiesInstitutionType: null,
	studiesCompleted: null,
	studiesEndYear: null,
	studiesDepartmentId: null,
	studiesProvinceId: null,
	studiesDistrictId: null,
	studiesAddress: null,
	studiesInstitutionName: null,
	representativeFullName: null,
	representativeEmail: null,
	representativeFamilyRelationshipId: null,
	representativeOccupation: null,
	representativePhone: null,
	majorId: null,
	facultyId: null,
	dniFilename: null,
	studyCertificateFilename: null,
	compromiseStudyCertificateFilename: null,
	documentaryProgressFiveYearFilename: null,
	statementNotCriminalFilename: null,
});