version: '3.1'
services:
  mysql:
    container_name: admision360_mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: '123'
      LANG: 'en_US.UTF-8'
      TZ: America/Lima
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
