USE admision360;

INSERT INTO admin(username, password, name) 
VALUES('admin', '$2a$12$UpFrqypEsvCV/ph5eqi8CepwOXsWny1Oo9cAb5s9U2PZJ7JTV.c2K', 'admin');

INSERT INTO family_relationship(name) 
VALUES('Padre'), 
('Madre'), 
('Hermano'), 
('Hermana'), 
('Tío'), 
('Tía');

INSERT INTO faculty(name) 
VALUES('Facultad de Medicina Humana'),
('Facultad de Ingenieria de Sistemas'),
('Facultad de Ingenieria Civil'),
('Facultad de Administración'),
('Facultad de Agronomía'),
('Facultad de Arquitectura'),
('Facultad de Ciencias'),
('Facultad de Ciencias Biológicas'),
('Facultad de Ciencias de la Comunicación, Turismo y Arqueología'),
('Facultad de Ciencias de la Educación y Humanidades'),
('Facultad de Ciencias Económicas y Negocios Internacionales'),
('Facultad de Contabilidad'),
('Facultad de Derecho y Ciencia Política'),
('Facultad de Enfermería'),
('Facultad de Farmacia y Bioquímica'),
('Facultad de Ingeniería Ambiental y Sanitaria'),
('Facultad de Ingeniería de Minas y Metalúrgica'),
('Facultad de Ingeniería Mecánica Eléctrica Electrónica'),
('Facultad de Ingeniería Pesquera y de Alimentos'),
('Facultad de Ingeniería Química y Petroquímica'),
('Facultad de Medicina Veterinaria y Zootecnia'),
('Facultad de Obstetricia'),
('Facultad de Odontología'),
('Facultad de Psicología');

INSERT INTO department(name) 
VALUES('Ica'),
('Lima'),
('Ayacucho');

INSERT INTO province(name, department_id) VALUES
('Ica', 1),
('Chincha', 1),
('Nasca', 1),
('Palpa', 1),
('Pisco', 1),
('Lima', 2),
('Barranca', 2),
('Cajatambo', 2),
('Canta', 2),
('Cañete', 2),
('Huaral', 2),
('Huarochirí', 2),
('Huaura', 2),
('Oyon', 2),
('Yuayos', 2),
('Huamanga', 3),
('Cangallo', 3),
('Huanca Sancos', 3),
('Huanta', 3),
('La Mar', 3),
('Lucanas', 3),
('Parinacochas', 3),
('Paucar del Sara Sara', 3),
('Sucre', 3),
('Víctor Fajardo', 3),
('Vilcashuamán', 3);

INSERT INTO district(name, province_id) VALUES
('Ica',1),
('La Tinguiña',1),
('Los Aquijes',1),
('Ocucaje',1),
('Pachacutec',1),
('Parcona',1),
('Pueblo Nuevo',1),
('Salas',1),
('San José de Los Molinos',1),
('San Juan Bautista',1),
('Santiago',1),
('Subtanjalla',1),
('Tate',1),
('Yauca del Rosario',1),
('Chincha Alta',2),
('Alto Laran',2),
('Chavin',2),
('Chincha Baja',2),
('El Carmen',2),
('Grocio Prado',2),
('Pueblo Nuevo',2),
('San Juan de Yanac',2),
('San Pedro de Huacarpana',2),
('Sunampe',2),
('Tambo de Mora',2),
('Nasca',3),
('Changuillo',3),
('El Ingenio',3),
('Marcona',3),
('Vista Alegre',3),
('Palpa',4),
('Llipata',4),
('Río Grande',4),
('Santa Cruz',4),
('Tibillo',4),
('Pisco',5),
('Huancano',5),
('Humay',5),
('Independencia',5),
('Paracas',5),
('San Andrés',5),
('San Clemente',5),
('Tupac Amaru Inca',5),
('Lima',6),
('Ancón',6),
('Ate',6),
('Barranco',6),
('Breña',6),
('Carabayllo',6),
('Chaclacayo',6),
('Chorrillos',6),
('Cieneguilla',6),
('Comas',6),
('El Agustino',6),
('Independencia',6),
('Jesús María',6),
('La Molina',6),
('La Victoria',6),
('Lince',6),
('Los Olivos',6),
('Lurigancho',6),
('Lurin',6),
('Magdalena del Mar',6),
('Pueblo Libre',6),
('Barranca',7),
('Paramonga',7),
('Pativilca',7),
('Supe',7),
('Supe Puerto',7),
('Cajatambo',8),
('Copa',8),
('Gorgor',8),
('Huancapon',8),
('Manas',8),
('Canta',9),
('Arahuay',9),
('Huamantanga',9),
('Huaros',9),
('Lachaqui',9),
('San Buenaventura',9),
('Santa Rosa de Quives',9),
('San Vicente de Cañete',10),
('Asia',10),
('Calango',10),
('Cerro Azul',10),
('Chilca',10),
('Coayllo',10),
('Imperial',10),
('Lunahuana',10),
('Mala',10),
('Nuevo Imperial',10),
('Huaral',11),
('Atavillos Alto',11),
('Atavillos Bajo',11),
('Aucallama',11),
('Chancay',11),
('Ihuari',11),
('Lampian',11),
('Pacaraos',11),
('San Miguel de Acos',11),
('Santa Cruz de Andamarca',11),
('Sumbilca',11),
('Veintisiete de Noviembre',11),
('Matucana',12),
('Antioquia',12),
('Callahuanca',12),
('Carampoma',12),
('Chicla',12),
('Cuenca',12),
('Huachupampa',12),
('Huanza',12),
('Huarochiri',12),
('Lahuaytambo',12),
('Huacho',13),
('Ambar',13),
('Caleta de Carquin',13),
('Checras',13),
('Hualmay',13),
('Huaura',13),
('Leoncio Prado',13),
('Paccho',13),
('Santa Leonor',13),
('Santa María',13),
('Sayan',13),
('Vegueta',13),
('Oyon',14),
('Andajes',14),
('Caujul',14),
('Cochamarca',14),
('Navan',14),
('Pachangara',14),
('Yauyos',15),
('Alis',15),
('Allauca',15),
('Ayaviri',15),
('Azángaro',15),
('Cacra',15),
('Carania',15),
('Catahuasi',15),
('Chocos',15),
('Ayacucho',16),
('Acocro',16),
('Acos Vinchos',16),
('Carmen Alto',16),
('Chiara',16),
('Ocros',16),
('Pacaycasa',16),
('Quinua',16),
('San José de Ticllas',16),
('San Juan Bautista',16),
('Santiago de Pischa',16),
('Socos',16),
('Tambillo',16),
('Vinchos',16),
('Jesús Nazareno',16),
('Andrés Avelino Cáceres Dorregaray',16),
('Cangallo',17),
('Chuschi',17),
('Los Morochucos',17),
('María Parado de Bellido',17),
('Paras',17),
('Totos',17),
('Sancos',18),
('Carapo',18),
('Sacsamarca',18),
('Santiago de Lucanamarca',18),
('Huanta',19),
('Ayahuanco',19),
('Huamanguilla',19),
('Iguain',19),
('Luricocha',19),
('Santillana',19),
('Sivia',19),
('Llochegua',19),
('Canayre',19),
('Uchuraccay',19),
('Pucacolpa',19),
('Chaca',19),
('San Miguel',20),
('Anco',20),
('Ayna',20),
('Chilcas',20),
('Chungui',20),
('Luis Carranza',20),
('Santa Rosa',20),
('Tambo',20),
('Samugari',20),
('Anchihuay',20),
('Oronccoy',20),
('Puquio',21),
('Aucara',21),
('Cabana',21),
('Carmen Salcedo',21),
('Chaviña',21),
('Chipao',21),
('Huac-Huas',21),
('Laramate',21),
('Leoncio Prado',21),
('Llauta',21),
('Lucanas',21),
('Ocaña',21),
('Otoca',21),
('Saisa',21),
('San Cristóbal',21),
('San Juan',21),
('San Pedro',21),
('San Pedro de Palco',21),
('Sancos',21),
('Santa Ana de Huaycahuacho',21),
('Santa Lucia',21),
('Coracora',22),
('Chumpi',22),
('Coronel Castañeda',22),
('Pacapausa',22),
('Pullo',22),
('Puyusca',22),
('San Francisco de Ravacayco',22),
('Upahuacho',22),
('Pausa',23),
('Colta',23),
('Corculla',23),
('Lampa',23),
('Marcabamba',23),
('Oyolo',23),
('Pararca',23),
('San Javier de Alpabamba',23),
('San José de Ushua',23),
('Sara Sara',23),
('Querobamba',24),
('Belén',24),
('Chalcos',24),
('Chilcayoc',24),
('Huacaña',24),
('Morcolla',24),
('Paico',24),
('San Pedro de Larcay',24),
('San Salvador de Quije',24),
('Santiago de Paucaray',24),
('Soras',24),
('Huancapi',25),
('Alcamenca',25),
('Apongo',25),
('Asquipata',25),
('Canaria',25),
('Cayara',25),
('Colca',25),
('Huamanquiquia',25),
('Huancaraylla',25),
('Hualla',25),
('Sarhua',25),
('Vilcanchos',25),
('Vilcas Huaman',25),
('Accomarca',25),
('Carhuanca',25),
('Concepción',25),
('Huambalpa',25),
('Independencia',25),
('Saurama',25),
('Vischongo',25);

INSERT INTO major(name, professional_school, faculty_id) VALUES
('Medicina Humana', 'Medicina Humana', 1),
('Ingenieria de Sistemas', 'Ingenieria de Sistemas', 2),
('Ingenieria de Civil', 'Ingenieria de Civil', 3),
('Administración', 'Administración', 4),
('Agronomía', 'Agronomía', 5),
('Arquitectura', 'Arquitectura', 6),
('Estadística', 'Estadística', 7),
('Física', 'Física', 7),
('Matemática e Informática', 'Matemática e Informática', 7),
('Biología', 'Biología', 8),
('Arqueología', 'Arqueología', 9),
('Ciencias de la Comunicación', 'Ciencias de la Comunicación', 9),
('Turismo', 'Turismo', 9),
('Ciencias de la Educación en Ciencias Biológicas y Química', 'Ciencias de la Educación', 10),
('Ciencias de la Educación en Educación Artística', 'Ciencias de la Educación', 10),
('Ciencias de la Educación en Educación Física', 'Ciencias de la Educación', 10),
('Ciencias de la Educación en Educación Inicial', 'Ciencias de la Educación', 10),
('Ciencias de la Educación en Educación Primaria', 'Ciencias de la Educación', 10),
('Ciencias de la Educación en Filosofía, Psicología y Ciencias Sociales', 'Ciencias de la Educación', 10),
('Ciencias de la Educación en Historia y Geografía', 'Ciencias de la Educación', 10),
('Ciencias de la Educación en Lengua y Literatura', 'Ciencias de la Educación', 10),
('Ciencias de la Educación en Matemática e Informática', 'Ciencias de la Educación', 10),
('Economía', 'Economía', 11),
('Negocios Internacionales', 'Negocios Internacionales', 11),
('Contabilidad', 'Contabilidad', 12),
('Derecho', 'Derecho', 12),
('Enfermería', 'Enfermería', 13),
('Farmacia y Bioquímica', 'Farmacia y Bioquímica', 14),
('Ingenieria Ambiental', 'Ingenieria Ambiental', 15),
('Ingeniería de Minas', 'Ingeniería de Minas', 16),
('Ingeniería Metalúrgica', 'Ingeniería Metalúrgica', 16),
('Ingeniería Electrónica','Ingeniería Electrónica',17),
('Ingeniería Mecánica Eléctrica','Ingeniería Mecánica Eléctrica',18),
('Ingeniería de Alimentos','Ingeniería de Alimentos',19),
('Ingenieria Pesquera','Ingenieria Pesquera',19),
('Ingeniería Química','Ingeniería Química',20),
('Ingenieria Petroquímica','Ingenieria Petroquímica',20),
('Medicina Veterinaria y Zootecnia','Medicina Veterinaria y Zootecnia',21),
('Obstetricia','Obstetricia',22),
('Odontología','Odontología',23),
('Psicología','Psicología',24);

INSERT INTO applicant(dni,name,surname,gender,birth_date,email,phone,applying_date,origin_district_id,origin_province_id,origin_department_id,mayor_id,faculty_id)
VALUES('12345678','Juan','Perez','M','1990-01-01','juan.perez@gmail.com','12345678','2023-01-01',1,1,1,1,1),
('12345679','Ana','Garcia','F','1990-01-01','ana.garcia@gmail.com','12345679','2023-01-01',1,1,1,1,1);
